# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesLangGen',
            fields=[
                ('movie_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=1000)),
                ('genres', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MovieBasicData',
            fields=[
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppFilmyFreaks.MoviesLangGen')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_poster', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppFilmyFreaks.MoviesLangGen')),
                ('release_date', models.DateTimeField()),
                ('runtime', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=50)),
                ('plot', models.CharField(max_length=1000)),
                ('actors', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('website_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppFilmyFreaks.MoviesLangGen')),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='movieslanggen',
            name='gen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFilmyFreaks.GenreList'),
        ),
        migrations.AddField(
            model_name='movieslanggen',
            name='lang_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFilmyFreaks.LanguagesList'),
        ),
    ]
