# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilmyFreaks', '0003_upcomingmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageslist',
            name='id',
        ),
        migrations.AddField(
            model_name='languageslist',
            name='lang_id',
            field=models.CharField(default='000', max_length=10, primary_key=True, serialize=False),
        ),
    ]
