# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilmyFreaks', '0004_auto_20170704_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrelist',
            name='id',
        ),
        migrations.AddField(
            model_name='genrelist',
            name='genre_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
