# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilmyFreaks', '0006_auto_20170704_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebasicdata',
            name='movie_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppFilmyFreaks.MoviesLangGen'),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='release_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='website_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='movieslanggen',
            name='gen_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movieslanggen',
            name='lang_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movieslanggen',
            name='movie_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
