# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilmyFreaks', '0007_auto_20170704_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='website_link',
        ),
    ]
