# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilmyFreaks', '0008_remove_moviedetails_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebasicdata',
            name='movie_poster',
            field=models.CharField(max_length=150),
        ),
    ]
